     
version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
    build:
        docker:
            - image: circleci/php:7-fpm-browsers-legacy
            - image: circleci/php:7.2.20
        steps:
            - checkout
            - run:
                name: "Run tests"
                command: phpdbg -qrr vendor/bin/phpunit --coverage-html build/coverage-report
            - store_artifacts:
                path:  build/coverage-report
            - run:
                command: |
                    mkdir -p ~/$CIRCLE_TEST_REPORTS/phpunit
                    php vendor/bin/phpunit --log-junit ~/$CIRCLE_TEST_REPORTS/phpunit/junit.xml --test-suffix=php/TestPlaceEvents.php --bootstrap vendor/autoload.php tests/.
                when: always

            - store_test_results:
                path: ~/$CIRCLE_TEST_REPORTS/phpunit
            - store_artifacts:
                path: ~/$CIRCLE_TEST_REPORTS/phpunit 
    test:
        docker:
            - image: circleci/php:7.2.20
        steps:
            - checkout
            - run:
                name: Run Tests
                command: |
                    mkdir -p ~$CIRCLE_TEST_REPORTS/phpunit
                    php vendor/bin/phpunit --log-junit ~$CIRCLE_TEST_REPORTS/phpunit/junit.xml --test-suffix=php/TestPlaceEvents.php --bootstrap vendor/autoload.php tests/.
                when: always
            - store_test_results:
                path: ~$CIRCLE_TEST_REPORTS/phpunit
            - store_artifacts:
                path: ~/phpunit

workflows:
    version: 2
    build_and_test:
        jobs:
        - build
        - test


